# This file tells Netlify how to build your site and where to find your functions.

[build]
  # From your screenshot, it looks like your build output folder is '.dist'.
  # If it's different (like 'public' or 'build'), change this line.
  publish = "dist"

[functions]
  # This tells Netlify to look for your function files inside the 'netlify/functions' folder.
  directory = "netlify/functions/"
